name: genio-tools
version: git
summary: Mediatek Genio Tools
description: |
  Flash, control or configure MediaTek boards, and in particular the Genio evaluation kits

license: MIT
adopt-info: genio-tools

confinement: classic
base: core22

environment:
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$PATH
  PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib

parts:
  genio-tools:
    plugin: python
    source: https://gitlab.com/mediatek/aiot/bsp/genio-tools.git
    source-type: git
    source-branch: main
    override-pull: |
      craftctl default
      git checkout "$(git tag --sort=-v:refname | grep -E '^[0-9]+(\.[0-9]+)*$' | head -n 1)" # Checkout latest stable version
      craftctl set version="$(git describe --tags --always)"
    override-build: |
      python3 setup.py install
      snapcraftctl build
    build-packages:
      - python3-setuptools
      - python3-setuptools-scm
    stage-packages:
      - fastboot
      - android-libziparchive
      - libpython3-stdlib
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - python3.10-minimal
    build-attributes:
      - enable-patchelf

apps:
  genio-flash:
    command: bin/genio-flash
  genio-config:
    command: bin/genio-config
  genio-board:
    command: bin/genio-board
  genio-multi-download-cli:
    command: bin/genio-multi-download-cli
