name: genio-tools
version: git
summary: Mediatek Genio Tools
description: |
  Flash, control or configure MediaTek boards, and in particular the Genio evaluation kits

platforms:
  amd64:
  arm64:

license: MIT
adopt-info: genio-tools

confinement: strict
base: core24

environment:
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$PATH
  PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib

parts:
  genio-tools:
    plugin: python
    source: https://gitlab.com/mediatek/aiot/bsp/genio-tools.git
    source-type: git
    source-branch: main
    build-packages:
      - python3-setuptools
      - python3-setuptools-scm
    stage-packages:
      - fastboot
      - android-libziparchive
      - libpython3-stdlib
      - libpython3.12-minimal
      - libpython3.12-stdlib
      - python3.12-minimal
    build-attributes:
      - enable-patchelf
    
  genio-setup:
    plugin: dump
    source: ./scripts
    organize:
      setup.sh: bin/setup.sh

plugs:
  home:
    interface: home
  network-observe:
    interface: network-observe
  raw-usb:
    interface: raw-usb
  hardware-observe:
    interface: hardware-observe

apps:
  genio-flash:
    command: bin/genio-flash
    plugs:
      - home
      - raw-usb
      - hardware-observe
  genio-config:
    command: bin/genio-config
    plugs:
      - home
      - hardware-observe
  genio-board:
    command: bin/genio-board
    plugs:
      - home
      - network-observe
      - raw-usb
      - hardware-observe
  genio-multi-download-cli:
    command: bin/genio-multi-download-cli
    plugs:
      - home
      - raw-usb
      - hardware-observe
  
  setup:
    command: bin/setup.sh
    plugs:
      - home
