name: genio-tools
version: git
summary: Mediatek Genio Tools
description: |
  Flash, control or configure MediaTek boards, and in particular the Genio evaluation kits

architectures:
  - build-on: amd64
  - build-on: arm64

license: MIT
adopt-info: genio-tools

confinement: strict
base: core22

environment:
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$PATH
  PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib

parts:
  genio-tools:
    plugin: python
    source: https://gitlab.com/mediatek/aiot/bsp/genio-tools.git
    source-type: git
    source-branch: main
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always)"
    override-build: |
      python3 setup.py install
      snapcraftctl build
    build-packages:
      - python3-setuptools
      - python3-setuptools-scm
    stage-packages:
      - fastboot
      - android-libziparchive
      - libpython3-stdlib
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - python3.10-minimal
    build-attributes:
      - enable-patchelf

plugs:
  adb-support:
    interface: adb-support
  home:
    interface: home
  network-observe:
    interface: network-observe
  raw-usb:
    interface: raw-usb
  system-files:
    interface: system-files
    read:
      - /etc/udev/rules.d/72-aiot.rules

apps:
  genio-flash:
    command: bin/genio-flash
    plugs:
      - adb-support
      - raw-usb
  genio-config:
    command: bin/genio-config
    plugs:
      - system-files
  genio-board:
    command: bin/genio-board
    plugs:
      - adb-support
      - network-observe
      - raw-usb
  genio-multi-download-cli:
    command: bin/genio-multi-download-cli
    plugs:
      - adb-support
      - raw-usb
